-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 21:27:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`user` (
  `id` VARCHAR(20) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `deleted` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`project` (
  `id` VARCHAR(20) NOT NULL,
  `leader_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL,
  `work_counts` INT NOT NULL,
  `deadline` DATE NOT NULL,
  `introduction` LONGTEXT NOT NULL,
  `deleted` TINYINT NOT NULL,
  `created_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`work` (
  `id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL,
  `introduction` MEDIUMTEXT NOT NULL,
  `deadline` DATE NOT NULL,
  `deleted` TINYINT NOT NULL,
  `created_date` DATE NOT NULL,
  `project_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_work_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_work_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `test`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL,
  `date` DATE NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `work_id` VARCHAR(20) NOT NULL,
  `work_project_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comment_work1_idx` (`work_id` ASC, `work_project_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_work1`
    FOREIGN KEY (`work_id` , `work_project_id`)
    REFERENCES `test`.`work` (`id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`leader_submit_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`leader_submit_work` (
  `submited` TINYINT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `deleted` TINYINT NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `work_id` VARCHAR(20) NOT NULL,
  `work_project_id` VARCHAR(20) NOT NULL,
  INDEX `fk_leader_submit_work_user1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`work_id`, `work_project_id`),
  CONSTRAINT `fk_leader_submit_work_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leader_submit_work_work1`
    FOREIGN KEY (`work_id` , `work_project_id`)
    REFERENCES `test`.`work` (`id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`profiles` (
  `date` DATETIME NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `github` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_profiles_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`user_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`user_project` (
  `joined_date` DATE NOT NULL,
  `leader` TINYINT NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `project_id` VARCHAR(20) NOT NULL,
  INDEX `fk_user_project_user1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`project_id`),
  CONSTRAINT `fk_user_project_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `test`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`user_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`user_work` (
  `work_code` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `work_id` VARCHAR(20) NOT NULL,
  `work_project_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`work_code`, `work_id`, `work_project_id`),
  INDEX `fk_user_work_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_work_work1_idx` (`work_id` ASC, `work_project_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_work_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_work_work1`
    FOREIGN KEY (`work_id` , `work_project_id`)
    REFERENCES `test`.`work` (`id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
