-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 00:10:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project_manage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_manage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_manage` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema thiet_bi_dien_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema thiet_bi_dien_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thiet_bi_dien_v2` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `project_manage` ;

-- -----------------------------------------------------
-- Table `project_manage`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_manage`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL,
  `work_counts` INT NOT NULL,
  `deadline` DATE NOT NULL,
  `introduction` LONGTEXT NOT NULL,
  `deleted` TINYINT NOT NULL,
  `created_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_manage`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_manage`.`work` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL,
  `introduction` MEDIUMTEXT NOT NULL,
  `deadline` DATE NOT NULL,
  `deleted` TINYINT NOT NULL,
  `created_date` DATE NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_work_project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_work_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project_manage`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_manage`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_manage`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `deleted` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_manage`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_manage`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL,
  `date` DATE NOT NULL,
  `work_id` INT NOT NULL,
  `work_project_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_work1_idx` (`work_id` ASC, `work_project_id` ASC) VISIBLE,
  INDEX `fk_comment_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_work1`
    FOREIGN KEY (`work_id` , `work_project_id`)
    REFERENCES `project_manage`.`work` (`id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_manage`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_manage`.`leader_submit_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_manage`.`leader_submit_work` (
  `submited` TINYINT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `deleted` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  `work_id` INT NOT NULL,
  `work_project_id` INT NOT NULL,
  INDEX `fk_leader_submit_work_user1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`work_id`, `work_project_id`),
  CONSTRAINT `fk_leader_submit_work_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_manage`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leader_submit_work_work1`
    FOREIGN KEY (`work_id` , `work_project_id`)
    REFERENCES `project_manage`.`work` (`id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_manage`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_manage`.`profiles` (
  `date` DATETIME NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `github` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_profiles_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_manage`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project_manage`.`user_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_manage`.`user_project` (
  `joined_date` DATE NOT NULL,
  `leader` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  INDEX `fk_user_project_user1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`project_id`),
  CONSTRAINT `fk_user_project_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_manage`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project_manage`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `thiet_bi_dien_v2` ;

-- -----------------------------------------------------
-- Table `thiet_bi_dien_v2`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thiet_bi_dien_v2`.`bill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `phone` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `address` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `create_time` DATETIME NOT NULL,
  `status` TINYINT NOT NULL,
  `deleted` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `thiet_bi_dien_v2`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thiet_bi_dien_v2`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `deleted` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `thiet_bi_dien_v2`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thiet_bi_dien_v2`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `price` DOUBLE NOT NULL,
  `create_date` DATE NOT NULL,
  `deleted` BIT(1) NOT NULL,
  `image` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `introduction` MEDIUMTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `specification` MEDIUMTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `sold_out` BIT(1) NOT NULL,
  `guarantee` INT NOT NULL,
  `category_id` INT NOT NULL,
  `bought` INT NOT NULL,
  `promotion` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Product_categoryId_Category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_categoryId_Category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `thiet_bi_dien_v2`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `thiet_bi_dien_v2`.`bill_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thiet_bi_dien_v2`.`bill_has_product` (
  `product_id` INT NOT NULL,
  `bill_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `product_price` DOUBLE NOT NULL,
  PRIMARY KEY (`product_id`, `bill_id`),
  INDEX `fk_BillHasProdcut_billId_Bill_id_idx` (`bill_id` ASC) VISIBLE,
  CONSTRAINT `fk_BillHasProdcut_billId_Bill_id`
    FOREIGN KEY (`bill_id`)
    REFERENCES `thiet_bi_dien_v2`.`bill` (`id`),
  CONSTRAINT `fk_BillHasProduct_productId_Product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `thiet_bi_dien_v2`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `thiet_bi_dien_v2`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thiet_bi_dien_v2`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `comment` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `product_id` INT NOT NULL,
  `accepted` TINYINT NOT NULL,
  `deleted` BIT(1) NOT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Comment_productId_Product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_productId_Product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `thiet_bi_dien_v2`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
